FROM --platform=linux/amd64 ubuntu:22.04
FROM --platform=linux/amd64 dfx_hardhat_node_base:latest

COPY ./artifacts /workspace/artifacts
COPY ./workspace_pj/* /workspace/

EXPOSE 8545
EXPOSE 4943

RUN chmod 744 ./bootstrap.sh
CMD ["./bootstrap.sh"]
