[workspace]
members = [
    "src/backend"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.75"
candid = "^0.10.4"
candid_parser = "^0.1.4"
ic-cdk = "0.13.2"
ic-stable-structures = "0.6.4"
serde = "1.0.163"
serde_json = "1.0.107"
