[package]
name = "ws_ic-cdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.9.6"
ic-cdk = "^0.11"
ic-cdk_v08 = { version = "^0.8", package = "ic-cdk" }
